version: "3.6"
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    hostname: influxdb
    networks:
      - lan
    ports:
      - 8086:8086
    environment:
      # INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "xxxxx"
      INFLUXDB_ADMIN_PASSWORD: "xxxxx"
      INFLUX_DB: "telegraf"
      # INFLUXDB_USER: "xxxxx"
      # INFLUXDB_USER_PASSWORD: "xxxxx"
    volumes:
      - influxdb-data:/var/lib/influxdb
  
  telegraf:
    image: telegraf:1.19.0
    depends_on:
      - influxdb
    container_name: telegraf
    restart: always
    networks:
      - lan
    ports:
      - "57000:57000"
    links:
      - influxdb:influxdb
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/grafana/tig/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    privileged: true

volumes:
  influxdb-data:

networks:
  lan:
