version: "3.6"
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    hostname: influxdb
    networks:
      - lan
    ports:
      - 8086:8086
    environment:
      # INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "xxxxx"
      INFLUXDB_ADMIN_PASSWORD: "xxxxx"
      INFLUX_DB: "telegraf"
      # INFLUXDB_USER: "xxxxx"
      # INFLUXDB_USER_PASSWORD: "xxxxx"
    volumes:
      - influxdb-data:/var/lib/influxdb
  
  telegraf:
    image: telegraf:1.19.0
    depends_on:
      - influxdb
    container_name: telegraf
    restart: always
    networks:
      - lan
    ports:
      - "57000:57000"
    links:
      - influxdb:influxdb
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/grafana/tig/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    privileged: true

  grafana:
    image: grafana/grafana:7.5.9
    depends_on:
      - influxdb
    container_name: grafana
    restart: always
    networks:
      - lan
    ports:
      - 3000:3000
    links:
      - influxdb:influxdb
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel, grafana-influxdb-08-datasource, grafana-kairosdb-datasource, grafana-piechart-panel, grafana-simple-json-datasource, grafana-worldmap-panel"
      GF_SECURITY_ADMIN_USER: admin  # nom de l'utilisateur créé par défaut pour accéder à Grafana
      GF_SECURITY_ADMIN_PASSWORD: admin  # mot de passe de l'utilisateur créé par défaut pour accéder à Grafana
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
  grafana-data:

networks:
  lan:
